/**
 *
 * $Id$
 */
package de.thm.evolvedb.graph.annotation.validation;

import de.thm.evolvedb.graph.annotation.AnnotationEntry;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.thm.evolvedb.graph.annotation.AnnotationTarget}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationTargetValidator {
	boolean validate();

	boolean validateTargetURI(String value);

	boolean validateAnnotations(EList<AnnotationEntry> value);
}
