package de.thm.evolvedb.graph.xtend;

import de.thm.evolvedb.graph.PropertyGraph;
import de.thm.evolvedb.migration.GraphNotAutomaticallyResolvableOperator;
import de.thm.evolvedb.migration.GraphNotAutomaticallyResolvableOperatorType;
import de.thm.evolvedb.migration.GraphPartiallyResolvableOperator;
import de.thm.evolvedb.migration.GraphPartiallyResolvableOperatorType;
import de.thm.evolvedb.migration.GraphResolvableOperator;
import de.thm.evolvedb.migration.GraphResolvableOperatorType;
import de.thm.evolvedb.migration.Migration;
import de.thm.evolvedb.migration.ProcessStatus;
import de.thm.evolvedb.migration.SchemaModificationOperator;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.sidiff.difference.symmetric.SymmetricDifference;

@SuppressWarnings("all")
public class GraphGEOGenerator {
  /**
   * Transactions that already have been visited.
   */
  private List<SchemaModificationOperator> processed;

  /**
   * Count of generated bytes.
   */
  private int generatedBytes = 0;

  /**
   * Count of generated files.
   */
  private int generatedFiles = 0;

  private long character = 0;

  /**
   * Generate the sql file.
   */
  public String doGenerate(final Resource resourceDifference, final IProgressMonitor progressMonitor) {
    final Function1<EObject, Boolean> _function = (EObject it) -> {
      return Boolean.valueOf((it instanceof Migration));
    };
    EObject _findFirst = IteratorExtensions.<EObject>findFirst(resourceDifference.getAllContents(), _function);
    Migration migration = ((Migration) _findFirst);
    SymmetricDifference difference = migration.getSymmetricDifference();
    Resource modelB = difference.getModelB();
    final Function1<EObject, Boolean> _function_1 = (EObject it) -> {
      return Boolean.valueOf((it instanceof PropertyGraph));
    };
    EObject _findFirst_1 = IteratorExtensions.<EObject>findFirst(modelB.getAllContents(), _function_1);
    PropertyGraph databaseSchemaB = ((PropertyGraph) _findFirst_1);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t\t");
    _builder.newLine();
    String content = _builder.toString();
    if ((this.processed == null)) {
      ArrayList<SchemaModificationOperator> _arrayList = new ArrayList<SchemaModificationOperator>();
      this.processed = _arrayList;
    }
    List<GraphResolvableOperator> resolvableOperators = migration.getGraphResolvableSMO();
    List<GraphPartiallyResolvableOperator> partiallyResolvable = migration.getGraphPartiallyResovableSMO();
    List<GraphNotAutomaticallyResolvableOperator> notAutomaticallyResolvable = migration.getGraphNotAutimaticallyResolvable();
    for (final GraphResolvableOperator resolvable : resolvableOperators) {
      {
        if ((Objects.equals(resolvable.getProcessStatus(), ProcessStatus.RESOLVED) && (!this.processed.contains(resolvable)))) {
          GraphResolvableOperatorType _displayName = resolvable.getDisplayName();
          String _plus = (_displayName + ": ");
          String _processResolvableOperator = this.processResolvableOperator(resolvable);
          String c = (_plus + _processResolvableOperator);
          String _content = content;
          String _xifexpression = null;
          if ((c != null)) {
            _xifexpression = c;
          } else {
            _xifexpression = "";
          }
          content = (_content + _xifexpression);
          String _content_1 = content;
          StringConcatenation _builder_1 = new StringConcatenation();
          content = (_content_1 + _builder_1);
        }
        this.processed.add(resolvable);
      }
    }
    return content;
  }

  public String processResolvableOperator(final GraphResolvableOperator operator) {
    Object _switchResult = null;
    GraphResolvableOperatorType _displayName = operator.getDisplayName();
    if (_displayName != null) {
      switch (_displayName) {
        case ADD_LABEL_TO_NODE_TYPE:
          return GraphChangeOperator.addLabelToNodeType(operator);
        case ADD_REFERENCE_OR_MEMBER:
          _switchResult = null;
          break;
        case CHANGE_NAME:
          return GraphChangeOperator.changeName(operator);
        case CHANGE_TYPE:
          return GraphChangeOperator.changeType(operator);
        case CREATE_CONSTRAINT_IN_LABEL:
          _switchResult = null;
          break;
        case CREATE_EDGE_TYPE:
          return GraphCreateOperator.createEdgeType(operator);
        case CREATE_NODE_TYPE:
          return GraphCreateOperator.createNodeType(operator);
        case CREATE_PROPERTY:
          return GraphCreateOperator.createProperty(operator);
        case CREATE_LABEL:
          return GraphCreateOperator.createLabel(operator);
        case WIDEN_NUMERIC_TYPE:
          _switchResult = null;
          break;
        case WIDEN_TEMPORAL_TYPE:
          _switchResult = null;
          break;
        default:
          String _name = operator.getDisplayName().name();
          return ("Operator unknown: " + _name);
      }
    } else {
      String _name = operator.getDisplayName().name();
      return ("Operator unknown: " + _name);
    }
    return ((String)_switchResult);
  }

  public String processPartiallyResolvableOperator(final GraphPartiallyResolvableOperator operator) {
    Object _switchResult = null;
    GraphPartiallyResolvableOperatorType _displayName = operator.getDisplayName();
    if (_displayName != null) {
      switch (_displayName) {
        case DELETE_EDGE_TYPE:
          return GraphDeleteOperator.deleteEdgeType(operator);
        case DELETE_LABEL:
          return GraphDeleteOperator.deleteLabel(operator);
        case DELETE_NODE_TYPE:
          return GraphDeleteOperator.deleteNodeType(operator);
        case REMOVE_PROPERTY_LABEL:
          return GraphDeleteOperator.deletePropertyLabel(operator);
        case REMOVE_PROPERTY_EDGE_TYPE:
          return GraphDeleteOperator.deletePropertyEdgeType(operator);
        case REMOVE_PROPERTY_NODE_TYPE:
          return GraphDeleteOperator.deletePropertyNodeType(operator);
        case NARROW_NUMERIC_TYPE:
          _switchResult = null;
          break;
        case NARROW_TEMPORAL_TYPE:
          _switchResult = null;
          break;
        case REMOVE_REFERENCE_OR_CONSTRAINT:
          _switchResult = null;
          break;
        case BINARY_ENCODING_CHANGE:
          _switchResult = null;
          break;
        default:
          String _name = operator.getDisplayName().name();
          return ("Operator unknown: " + _name);
      }
    } else {
      String _name = operator.getDisplayName().name();
      return ("Operator unknown: " + _name);
    }
    return ((String)_switchResult);
  }

  public String processNotAutomaticallyResolvableOperator(final GraphNotAutomaticallyResolvableOperator operator) {
    GraphNotAutomaticallyResolvableOperatorType _displayName = operator.getDisplayName();
    if (_displayName != null) {
      switch (_displayName) {
        case MOVE_COMBINED:
          return GraphChangeOperator.moveCombined(operator);
        case MOVE_EDGE_TYPE:
          return GraphChangeOperator.moveEdgeType(operator);
        case MOVE_LABEL:
          return GraphChangeOperator.moveLabel(operator);
        case MOVE_NODE_TYPE:
          return GraphChangeOperator.moveNodeType(operator);
        case MOVE_PROPERTY:
          return GraphChangeOperator.moveProperty(operator);
        default:
          String _name = operator.getDisplayName().name();
          return ("Operator unknown: " + _name);
      }
    } else {
      String _name = operator.getDisplayName().name();
      return ("Operator unknown: " + _name);
    }
  }
}
