source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               lib/kotlin-stdlib-jdk8-2.2.21.jar,\
               lib/openai-java-4.8.0.jar,\
               lib/openai-java-client-okhttp-4.8.0.jar,\
               lib/openai-java-core-4.8.0.jar,\
               lib/kotlin-stdlib-2.2.21.jar,\
               lib/jackson-annotations-2.20.jar,\
               lib/jackson-core-2.20.1.jar,\
               lib/jackson-databind-2.20.1.jar,\
               lib/jackson-module-kotlin-2.20.1.jar,\
               lib/jackson-datatype-jdk8-2.20.1.jar,\
               lib/jackson-datatype-jsr310-2.20.1.jar,\
               lib/logging-interceptor-5.3.2.jar,\
               lib/okhttp-5.3.2.jar,\
               lib/okhttp-4.12.0.jar,\
               lib/okio-3.16.4.jar,\
               lib/okio-jvm-3.16.4.jar,\
               lib/kotlin-reflect-2.2.21.jar
