/**
 *
 * $Id$
 */
package de.thm.evolvedb.migration.validation;

import de.thm.evolvedb.migration.SchemaModificationOperator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.resource.Resource;

import org.sidiff.difference.symmetric.Change;
import org.sidiff.difference.symmetric.SymmetricDifference;

/**
 * A sample validator interface for {@link de.thm.evolvedb.migration.Migration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MigrationValidator {
	boolean validate();

	boolean validateSymmetricDifference(SymmetricDifference value);
	boolean validateSchemaModificationOperators(EList<SchemaModificationOperator> value);
	boolean validateSymetricDifferenceModel(Resource value);
	boolean validateUriSymetricDifferenceModel(String value);
	boolean validateUnassignedChanges(EList<Change> value);
}
