/**
 *
 * $Id$
 */
package de.thm.evolvedb.migration.validation;

import de.thm.evolvedb.migration.ComplexResolveOptions;
import de.thm.evolvedb.migration.NotAutomaticallyResolvableOperatorType;

/**
 * A sample validator interface for {@link de.thm.evolvedb.migration.NotAutomaticallyResolvable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NotAutomaticallyResolvableValidator {
	boolean validate();

	boolean validateDisplayName(NotAutomaticallyResolvableOperatorType value);
	boolean validateResolveOptions(ComplexResolveOptions value);
}
