/**
 *
 * $Id$
 */
package de.thm.evolvedb.migration.validation;

import de.thm.evolvedb.migration.ColumnOptions;
import de.thm.evolvedb.migration.PartiallyResolvableOperatorType;

/**
 * A sample validator interface for {@link de.thm.evolvedb.migration.PartiallyResolvable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PartiallyResolvableValidator {
	boolean validate();

	boolean validateDisplayName(PartiallyResolvableOperatorType value);
	boolean validateResolveOptions(ColumnOptions value);
}
