/**
 *
 * $Id$
 */
package de.thm.evolvedb.migration.validation;

import de.thm.evolvedb.migration.Migration;
import de.thm.evolvedb.migration.ProcessStatus;

import org.eclipse.emf.common.util.EList;

import org.sidiff.difference.symmetric.SemanticChangeSet;

/**
 * A sample validator interface for {@link de.thm.evolvedb.migration.SchemaModificationOperator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SchemaModificationOperatorValidator {
	boolean validate();

	boolean validateSemanticChangeSets(EList<SemanticChangeSet> value);
	boolean validateProcessStatus(ProcessStatus value);
	boolean validateMigration(Migration value);
	boolean validateDescription(String value);
}
