#

pluginName = de.thm.evolvedb.graph.annotation Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Annotation_type = Annotation
_UI_AnnotationEntry_type = Entry
_UI_AnnotationTarget_type = Target
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Annotation_annotationTarget_feature = Annotation Target
_UI_AnnotationEntry_key_feature = Key
_UI_AnnotationEntry_value_feature = Value
_UI_AnnotationEntry_source_feature = Source
_UI_AnnotationTarget_targetURI_feature = Target URI
_UI_AnnotationTarget_annotations_feature = Annotations
_UI_Unknown_feature = Unspecified

